spring:
  datasource:
    name: @jdbc.name@
    username: @jdbc.usename@
    password: @jdbc.password@
    url: @jdbc.url@
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 4
      max-active: 10
      max-wait: 1000

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
