spring:
  profiles:
    active: @profileActive@
  jackson:
      default-property-inclusion: non_null
  http:
    encoding:
      force: true
      force-request: true
      force-response: true
    multipart:
      max-file-size: 10MB
      file-size-threshold: 5MB
logging:
  level:
    org:
      springframework:
        web: debug
    cn:
      cnic:
        trackrecord: debug

server:
  tomcat:
    uri-encoding: utf-8
