track:
  file:
    upload-path: /var/track_record/upload
    unzip-path: /var/track_record/unzip

plugin:
  ffmpeg:
    conf:
      path: /usr/bin/ffmpeg
  hadoop:
    conf:
      home-dir: /usr/local/hadoop
      local-tmp-dir: /var/track_record/hadoop/tmp
      store-path: gpstracks
  lucene:
    conf:
      index-path: /var/track_record/lucene/index


