spring:
  jackson:
      default-property-inclusion: non_null
  http:
    encoding:
      force: true
      force-request: true
      force-response: true
    multipart:
      max-file-size: 1024MB
      file-size-threshold: 1024MB
      max-request-size: 1024MB
logging:
  level:
    org:
      springframework:
        web: @log.level@
    cn:
      cnic:
        trackrecord: @log.level@

server:
  tomcat:
    uri-encoding: utf-8

jwt:
  expiration: @jwt.expiration@
  header: @jwt.header@
  query-param: @jwt.query-param@
  secret: @jwt.secret@
  token-head: @jwt.token-head@

track:
  file:
    upload-path: @track.file.upload-path@
    unzip-path: @track.file.unzip-path@
    fixed-delay: @track.file.fixed-delay@
    tries: @track.file.tries@
    route-record-file-name: @track.file.route-record-file-name@
    track-detail-file-name: @track.file.track-detail-file-name@

