logging:
  level:
    org:
      springframework:
        web: debug
spring:
  jackson:
    default-property-inclusion: non_empty
  http:
    encoding:
      force: true
      force-request: true
      force-response: true
server:
  tomcat:
    uri-encoding: utf-8

