logging:
  level:
    org:
      springframework:
        web: debug
spring:
  jackson:
    default-property-inclusion: non_null
  http:
    encoding:
      force: true
      force-request: true
      force-response: true
    multipart:
      max-file-size: 10MB
      file-size-threshold: 5MB
server:
  tomcat:
    uri-encoding: utf-8

track:
  file:
    upload-path: D:/track_file
    unzip-path: D:/track_file
banner:
  image:
    location:


